# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Payment Function App

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: src/Stushbr.Function.Payment
  FUNCTION_NAME: azfun-stushbr-payment
  RG_NAME: rg-stushbr

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup DotNet ${{ vars.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Update nuget source
        run: dotnet nuget update source "github" --username ${{ github.actor }} --password ${{ secrets.NUGET_ACCESS }} --store-password-in-clear-text

      - name: Build with dotnet
        shell: bash
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FUNCTION_NAME }}
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4.1.7
        with:
          name: ${{ env.FUNCTION_NAME }}

      - name: Deploy to Azure Web App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTION_NAME }}
          slot-name: production
          publish-profile: ${{ secrets.PAYMENT_FUNCTION_PUBLISH_PROFILE }}
          package: .

  setup-function:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set app settings
        run: |
            az functionapp config appsettings set --name ${{ env.FUNCTION_NAME }} --resource-group ${{ env.RG_NAME }} --settings "Application__TildaWebhookSecret=${{ secrets.PAYMENT_FUNCTION_APP_SETTINGS_TILDA_WEBHOOK_SECRET }} AzureFunctionsJobHost__logging__logLevel__default=${{ vars.PAYMENT_FUNCTION_APP_SETTINGS_LOG_LEVEL }} SendPulse__HookUrl=${{ secrets.PAYMENT_FUNCTION_APP_SETTINGS_SENDPULSE_HOOK_URL }} Telegram__AccessKey=${{ secrets.PAYMENT_FUNCTION_APP_SETTINGS_TELEGRAM_ACCESS_KEY }}"
