name: NPM Build Stushbr.PaymentsGatewayWeb ClientApp

on:
  push:
    branches:
      - master
    paths:
      - 'src/payments-gateway/Stushbr.PaymentsGatewayWeb/ClientApp/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache npm packages
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      run: npm ci --prefix ./src/payments-gateway/Stushbr.PaymentsGatewayWeb/ClientApp

    - name: Build
      run: npm run build --prefix ./src/payments-gateway/Stushbr.PaymentsGatewayWeb/ClientApp
